name: uth_assistant_app
description: "Sinh viên UTH - Ứng dụng dành cho sinh viên Đại học GTVT TP. Hồ Chí Minh"
publish_to: 'none' 

version: 1.0.0+1

environment:
  # Sửa lại cú pháp và phiên bản SDK cho hợp lệ
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  screen_protector: 1.4.7
  file_picker: ^8.0.0  # Để chọn file từ máy
  http_parser: ^4.0.2  # Để định nghĩa MediaType (pdf/doc)
  flutter_svg: ^2.0.10+1
  flutter_secure_storage: ^9.0.0
  image_picker: ^1.0.7
  mime: ^1.0.5
  intl: ^0.19.0
  cached_network_image: ^3.3.1
  # Đã xóa dòng http: ^1.1.0 bị trùng lặp
  http: ^1.2.1 
  url_launcher: ^6.3.0
  webview_flutter: ^4.7.0 # Hoặc phiên bản mới nhất
  flutter_staggered_grid_view: ^0.7.0 # Hoặc phiên bản mới nhất
  cupertino_icons: ^1.0.8
  jwt_decoder: ^2.0.1
  photo_view: ^0.15.0  # Thư viện xem ảnh với zoom/pan
  shared_preferences: ^2.2.2
  # Firebase packages cho push notification
  firebase_core: ^3.8.1
  firebase_messaging: ^15.1.5
  flutter_local_notifications: ^18.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Tôi đã sửa lại phiên bản này về ^4.0.0 (phổ biến)
  # Nếu bạn cố ý dùng ^5.0.0, bạn có thể sửa lại
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  # Đảm bảo thụt đầu dòng chính xác (2 dấu cách)
  assets:
    - assets/images/
    - assets/images_pic/

  fonts:
    - family: LazyDog
      fonts:
        - asset: fonts/LazyDog-Regular.ttf
        # - asset: fonts/LazyDog-Bold.ttf
        #   weight: 700
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf
    - family: BeVietnamPro
      fonts:
        - asset: fonts/BeVietnamPro-Medium.ttf
          weight: 700
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-BoldItalic.ttf
          weight: 700
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-BoldItalic.ttf
          weight: 700

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  # Adaptive icon cho Android 8+ (2 lớp riêng)
  adaptive_icon_background: "#2A8683"
  adaptive_icon_foreground: "assets/images/ic_foreground.png"
  remove_alpha_ios: true
